######################################################################
# Automatically generated by qmake (1.07a) Wed Sep 29 02:19:56 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += plotter.h
SOURCES += main.cpp plotter.cpp qmake_image_collection.cpp
