######################################################################
# Automatically generated by qmake (1.07a) Tue Sep 28 09:35:34 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += plotter.h
SOURCES += main.cpp plotter.cpp qmake_image_collection.cpp
